### ISSUE TITLE
How can humans be generated?

### ISSUE THREAD

**Issue by StGorazd** [Unity-Technologies/AnthroNet#2]
Hello,
I am very interested in your work.

Is there a tutorial available on how to use your generator or where to find it? I am particularly interested in generating humans through anthropometric measurements.

Thanks for the excellent work!

**Comment by m-junaida** [comment]
Hi, I also want to do the same. 
I have body measurements available. I want to generate 3D meshes using those with AnthroNet. 

Thanks in advance. Really interesting work!

**Comment by salehe-ee** [comment]
Thank you for your interest in this work. Currently we are not offering this feature. However by referring to our paper, the Unity Perception package documentation, and the Unity Synthetic Humans Package you may be able to replicate the measurements.
